const chaiValues = {
  spacing: {
    0: "0px",
    1: "2px",
    2: "4px",
    3: "6px",
    4: "8px",
    5: "10px",
    6: "12px",
    8: "16px",
    10: "20px",
    12: "24px",
    16: "32px",
    20: "40px",
    24: "48px",
  },
  fontSize: {
    xs: "12px",
    sm: "14px",
    base: "16px",
    lg: "18px",
    xl: "20px",
    "2xl": "24px",
    "3xl": "30px",
  },
  namedColors: {
    black: "#000000",
    white: "#ffffff",
    red: "#ef4444",
    blue: "#3b82f6",
    green: "#22c55e",
    yellow: "#facc15",
    gray: "#6b7280",
    pink: "#ec4899",
    purple: "#a855f7",
    orange: "#f97316",
  },
  spacingMap: {
    p: ["padding"],
    px: ["padding-left", "padding-right"],
    py: ["padding-top", "padding-bottom"],
    pt: ["padding-top"],
    pr: ["padding-right"],
    pb: ["padding-bottom"],
    pl: ["padding-left"],
    m: ["margin"],
    mx: ["margin-left", "margin-right"],
    my: ["margin-top", "margin-bottom"],
    mt: ["margin-top"],
    mr: ["margin-right"],
    mb: ["margin-bottom"],
    ml: ["margin-left"],
  },
  displayMap: {
    block: "block",
    inline: "inline",
    "inline-block": "inline-block",
    flex: "flex",
    grid: "grid",
    hidden: "none",
  },

  // those three are little different from each other 
  alignItemsMap: {
    start: "flex-start",
    end: "flex-end",
    center: "center",
    baseline: "baseline",
    stretch: "stretch",
  },
  justifyContentMap: {
    start: "flex-start",
    end: "flex-end",
    center: "center",
    between: "space-between",
    around: "space-around",
    evenly: "space-evenly",
  },
  textAlignMap: {
    left: "left",
    center: "center",
    right: "right",
    justify: "justify",
  },


  borderRadiusMap: {
    none: "0px",
    sm: "2px",
    base: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
    full: "9999px",
  },
  fontWeightMap: {
    thin: "100",
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    black: "900",
  },
  sizeMap: {
    "h-screen": { property: "height", value: "100vh" },
    "min-h-screen": { property: "min-height", value: "100vh" },
    "w-full": { property: "width", value: "100%" },
    "h-full": { property: "height", value: "100%" },
  },


};

export { chaiValues };
